@startuml
'https://plantuml.com/class-diagram

class Student {
last_name: String
first_name: String
paternal_name: String
id: Integer
phone: String
git: String
telegram: String
email: String
--
+{static}valid_phone?(String): Boolean
+{static}valid_name?(String): Boolean
+{static}valid_account?(String): Boolean
+{static}valid_email?(String): Boolean
+initialize(Hash)
+{static}pars_str(String)
+shortName():String
+contact():String
+getInfo():String
+validate?(): Bollean
+set_contacts(Hash)
+to_s(): String
--Getters--
+phone():String
+first_name(): String
+last_name(): String
+paternal_name(): String
+git=(): String
+telegram(): String
+email(): String
--Setters--
+phone=(String)
+first_name=(String)
+last_name=(String)
+paternal_name=(String)
+git=(String)
+telegram=(String)
+email=(String)
}

class StudentShort{
id: Integer
git: String
contact: String
initials: String
--
+initialize(Student)
+{static}from_str(id, str)
+to_s():String
--Getters--
+id(): Integer
+git(): String
+contact(): String
+initials(): String
}
class Data_list{
sel_objects:Array
list:Array
--
+initialize(Array)
+select(Integer):Array
+get_selected():Array
+get_data():Array
#get_names()
#table_fields(Object):Array
--Getters--
-sel_objects():Array
+list():Array
--Setters--
-sel_objects=(Array))
+list=(Array)
}

class Data_table{
table:Array
stroka_count:Integer
stolb_count:Integer
--
+initialize(Table)
+get_elem(Integer, Integer):String
--Getters--
-table()
+stroka_count():Integer
+stolb_count():Integer
--Setters--
-table()
-stroka_count=(Integer)
-stolb_count=(Integer)
}

class Data_list_student_short{
--
+initialize(Array)
+get_names():Data_table
#table_fields(Objects):Array
}

class main{
read_from_txt(String):List<Student>
write_to_txt(String, List<Student>):
}
StudentShort ^-- Student
Data_list ^-- Data_list_student_short
Data_list_student_short o--StudentShort
Data_list ..>Data_table
@enduml

